services:
  mongo:
    image: mongo:7
    container_name: barber_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: barber_reservation

volumes:
  mongo_data:
